### ISSUE TITLE
InvalidRamlError on raml file: Unexpected key 'displayName' 

### ISSUE THREAD

**Issue by raspacorp** [phoenixnap/springmvc-raml-plugin#166]
I am trying to use the plugin to generate an spring mvc client, it seems it doesn't like my raml file.

My raml file starts like this:

```
#%RAML 0.8
title: My API
version: "1"
baseUri: "http://localhost:8080"
mediaType: application/json
resourceTypes: 
    - 
        refDataCollection: 
            displayName: refDataCollection
    - 
        refData: 
            displayName: refData
... 
```

I am using this version of your plugin:

```
<groupId>com.phoenixnap.oss</groupId>
                <artifactId>springmvc-raml-plugin</artifactId>
                <version>0.10.5</version>
```
This is the error I am getting:

```
Exception in thread "main" InvalidRamlError on raml file file:/.../myAPI.raml {errors=[Unexpected key 'displayName'. Options are : "baseUriParameters" or "body" or "description" or "headers" or "is" or "protocols" or "queryParameters" or "responses" or "securedBy" or "usage" or /<<(.+?)>>/ -- file:/.../myAPI.raml [line=37, col=13], Unexpected key 'displayName'. Options are : "baseUriParameters" or "body" or "description" or "headers" or "is" or "protocols" or "queryParameters" or "responses" or "securedBy" or "usage" or /<<(.+?)>>/ -- file:/.../myAPI.raml [line=40, col=13], Unexpected key 'displayName'. Options are : "baseUriParameters" or "body" or "description" or "headers" or "is" or "protocols" or "queryParameters" or "responses" or "securedBy" or "usage" or /<<(.+?)>>/ -- file:/.../myAPI.raml [line=43, col=13], Unexpected key 'displayName'. Options are : "baseUriParameters" or "body" or "description" or "headers" or "is" or "protocols" or "queryParameters" or "responses" or "securedBy" or "usage" or /<<(.+?)>>/ -- file:/.../myAPI.raml [line=46, col=13], Unexpected key 'displayName'. Options are : "baseUriParameters" or "body" or "description" or "headers" or "is" or "protocols" or "queryParameters" or "responses" or "securedBy" or "usage" or /<<(.+?)>>/ -- file:/.../myAPI.raml [line=49, col=13], Unexpected key 'displayName'. Options are : "baseUriParameters" or "body" or "description" or "headers" or "is" or "protocols" or "queryParameters" or "responses" or "securedBy" or "usage" or /<<(.+?)>>/ -- file:/.../myAPI.raml [line=52, col=13], Unexpected key 'displayName'. Options are : "baseUriParameters" or "body" or "description" or "headers" or "is" or "protocols" or "queryParameters" or "responses" or "securedBy" or "usage" or /<<(.+?)>>/ -- file:/.../myAPI.raml [line=55, col=13], Unexpected key 'displayName'. Options are : "baseUriParameters" or "body" or "description" or "headers" or "is" or "protocols" or "queryParameters" or "responses" or "securedBy" or "usage" or /<<(.+?)>>/ -- file:/.../myAPI.raml [line=58, col=13]]}
	at com.phoenixnap.oss.ramlapisync.raml.RamlModelFactoryOfFactories.createRamlModelFactoryFor(RamlModelFactoryOfFactories.java:103)
	at com.phoenixnap.oss.ramlapisync.raml.RamlModelFactoryOfFactories.createRamlModelFactoryFor(RamlModelFactoryOfFactories.java:70)
	at com.phoenixnap.oss.ramlapisync.generation.rules.RamlLoader.loadRamlFromFile(RamlLoader.java:45)
...
```

**Comment by 88SergiiOliinyk** [comment]
Faced the same issue

**Comment by champagne** [comment]
Hi @raspacorp ,

Please attach your full raml file.

I have just tried your raml snippet with springmvc-raml-plugin 0.10.7, it works fine.
raml file:
`#%RAML 0.8
  title: My API
  version: "1"
  baseUri: "http://localhost:8080"
  mediaType: application/json
  resourceTypes:
  - 
    refDataCollection: 
      displayName: refDataCollection
  - 
    refData: 
      displayName: refData

  /drinks:
`

BR,
Xiangbin HAN

**Comment by raspacorp** [comment]
Sorry I am not working on that project anymore and no longer have access to the raml file, I will close the issue. Thanks for your help.
