### ISSUE TITLE
Multi-files Json Schema not supported

### ISSUE THREAD

**Issue by Leroy14** [phoenixnap/springmvc-raml-plugin#43]
Hi,
I've a schema A ("A.json") which references a schema B using "$ref" attributes. like for example:
```json
{
   "$schema": "http://json-schema.org/draft-04/schema",
   "title": "Collection of B",
   "type": "array",
   "uniqueItems": true,
   "items": {
      "$ref": "B.json"
   }
}
```
Files A.json and B.json are in the same directory 'schemas'.
I've a RAML referencing the schema A like:
```raml
...
schemas:
  - A: !include schemas/A.json
...
/a:
  post:
    body:
      application/json:
        schema: A
... 
```
When I call the following plugin execution:
```xml
...
     <plugin>
        <groupId>com.phoenixnap.oss</groupId>
        <artifactId>springmvc-raml-plugin</artifactId>
        <version>0.5.1</version>
        <configuration>
          <ramlPath>src/main/resources/webapp/meta-data/api.raml</ramlPath>
        <rule>com.phoenixnap.oss.ramlapisync.generation.rules.Spring4ControllerInterfaceRule</rule>
          <ruleConfiguration>
          </ruleConfiguration>
        </configuration>
        <executions>
          <execution>
            <id>generate-springmvc-endpoints</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>generate-springmvc-endpoints</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
I get the following exception:
```java
java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URI.toURL(URI.java:1088)
        at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:65)
        at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:47)
        at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:94)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:59)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
        at org.jsonschema2pojo.rules.ArrayRule.apply(ArrayRule.java:81)
        at org.jsonschema2pojo.rules.ArrayRule.apply(ArrayRule.java:37)
        at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:107)
        at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:39)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
        at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
        at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:132)
        at com.phoenixnap.oss.ramlapisync.naming.SchemaHelper.buildBodyJCodeModel(SchemaHelper.java:396)
        at com.phoenixnap.oss.ramlapisync.naming.SchemaHelper.mapSchemaToPojo(SchemaHelper.java:361)
        at com.phoenixnap.oss.ramlapisync.data.ApiMappingMetadata.parseResponse(ApiMappingMetadata.java:159)
        at com.phoenixnap.oss.ramlapisync.data.ApiMappingMetadata.<init>(ApiMappingMetadata.java:69)
        at com.phoenixnap.oss.ramlapisync.data.ApiMappingMetadata.<init>(ApiMappingMetadata.java:74)
        at com.phoenixnap.oss.ramlapisync.data.ApiControllerMetadata.addApiCall(ApiControllerMetadata.java:56)
        at com.phoenixnap.oss.ramlapisync.generation.RamlParser.checkResource(RamlParser.java:155)
        at com.phoenixnap.oss.ramlapisync.generation.RamlParser.extractControllers(RamlParser.java:95)
        at com.phoenixnap.oss.ramlapisync.plugin.SpringMvcEndpointGeneratorMojo.generateEndpoints(SpringMvcEndpointGeneratorMojo.java:147)
        at com.phoenixnap.oss.ramlapisync.plugin.SpringMvcEndpointGeneratorMojo.execute(SpringMvcEndpointGeneratorMojo.java:268)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
What is wrong with this approach to use Multi-file json schema?
I can provide a maven project to reproduce the issue if needed.

**Comment by kurtpa** [comment]
Hi Leroy, 

If you have the maven project handy i would appreciate it, if not i'll build it myself :)

**Comment by kurtpa** [comment]
Reproduced via unit test :)

**Comment by kurtpa** [comment]
Changing the $ref to be more explicit. In my case, the json files are in a folder called "pojogen" in the classpath.

```
"items": {
      "$ref": "classpath:pojogen/B.json"
   }
```

This was parsed successfully

**Comment by kurtpa** [comment]
It will also work if you use absolute URLs such as

'''
"items": {
      "$ref": "http://test-url/stuff/B.json"
   }
'''

From the code i'm seeing in Uri.toURL() and ContentResolver.resolve(URI) i'll be adding a property to the GenerationMojo in 0.5.2 that will allow us to specify a base location for the files. This will internally convert it to a "file:{targetDir}" which will be used by Jsonschema2Pojo

**Comment by kurtpa** [comment]
fix will be released with 0.5.2

**Comment by Leroy14** [comment]
Thank a lot for your quick answer. I'll use your workaround waiting for the 0.5.2 version.
BR,

**Comment by kurtpa** [comment]
Welcome, I'll test a bit more tonight and hopefully release tomorrow. With 0.5.2 if you specify the base folder (schemaLocation) in the plugin configuration, relative $refs should work out the box without the need to add classpath:
