### ISSUE TITLE
ParameterizedTypeImpl cannot be cast to java.lang.Class

### ISSUE THREAD

**Issue by christophlingg** [phoenixnap/springmvc-raml-plugin#44]
I used this configuration to generate RAML from my Spring controllers:

```
<plugin>
	<groupId>com.phoenixnap.oss</groupId>
	<artifactId>springmvc-raml-plugin</artifactId>
	<version>0.5.1</version>
	<configuration>
		<outputRamlFilePath>/src/main/resources/public/raml/api.raml</outputRamlFilePath>
		<restBasePath>https://api.komoot.de/v007/</restBasePath>
		<includeGlobalMediaType>false</includeGlobalMediaType>
		<restrictOnMediaType>false</restrictOnMediaType>
	</configuration>
	<executions>
		<execution>
			<id>generate-springmvc-api-docs</id>
			<phase>compile</phase>
			<goals>
				<goal>generate-springmvc-api-docs</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

> [ERROR] Failed to execute goal com.phoenixnap.oss:springmvc-raml-plugin:0.5.1:generate-springmvc-api-docs (generate-springmvc-api-docs) on project controller-v007: A type incompatibility occured while executing com.phoenixnap.oss:springmvc-raml-plugin:0.5.1:generate-springmvc-api-docs: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class

This is the strack trace:
```
Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
	at com.phoenixnap.oss.ramlapisync.data.ApiParameterMetadata.<init>(ApiParameterMetadata.java:166)
	at com.phoenixnap.oss.ramlapisync.parser.SpringMvcResourceParser.getApiParameters(SpringMvcResourceParser.java:279)
	at com.phoenixnap.oss.ramlapisync.parser.ResourceParser.extractRequestBodyFromMethod(ResourceParser.java:197)
	at com.phoenixnap.oss.ramlapisync.parser.SpringMvcResourceParser.extractAndAppendResourceInfo(SpringMvcResourceParser.java:452)
	at com.phoenixnap.oss.ramlapisync.parser.ResourceParser.getMethodsFromService(ResourceParser.java:86)
	at com.phoenixnap.oss.ramlapisync.parser.ResourceParser.extractResourceInfo(ResourceParser.java:403)
	at com.phoenixnap.oss.ramlapisync.generation.RamlGenerator.lambda$generateRamlForClasses$2(RamlGenerator.java:119)
	at com.phoenixnap.oss.ramlapisync.generation.RamlGenerator$$Lambda$1/1506804235.accept(Unknown Source)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at com.phoenixnap.oss.ramlapisync.generation.RamlGenerator.generateRamlForClasses(RamlGenerator.java:118)
	at com.phoenixnap.oss.ramlapisync.plugin.SpringMvcRamlApiSyncMojo.generateRaml(SpringMvcRamlApiSyncMojo.java:110)
	at com.phoenixnap.oss.ramlapisync.plugin.SpringMvcRamlApiSyncMojo.execute(SpringMvcRamlApiSyncMojo.java:143)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
```

Any idea what I can do?

**Comment by jtheuer** [comment]
I know this error from my previous reflection games - I guess that the parser cannot deal with all fancy types of generics. If you really want to follow this path you would have to dig through the source code. Maybe a better first step is report it and ask for a more verbose error message.

**Comment by kurtpa** [comment]
I've just made a commit on the 0.5.2 release candidate (feature branch: add raml style check) - I dont have the data to replicate your issue, could you clone this locally and try it out or send me your RAML so that i can use it for generation
