### ISSUE TITLE
The plugin throws ArrayIndexOutofBoundsException! Causing the plugin to fail. Please rectify.

### ISSUE THREAD

**Issue by vishalmahuli** [phoenixnap/springmvc-raml-plugin#75]

**Comment by kurtpa** [comment]
Please provide a meaningful description,  stack trace and sample source file otherwise i will have no choice but to close this issue

**Comment by vishalmahuli** [comment]
Please find the stack trace:


Execution generate-springmvc-api-docs of goal
com.phoenixnap.oss:springmvc-raml-plugin:0.2.1:generate-springmvc-api-docs
failed: 0

at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)

at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)

at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)

at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)

at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)

at
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)

at
org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)

at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)

at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)

at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)

at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)

at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)

at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)

at
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)

at
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)

at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

Caused by: org.apache.maven.plugin.PluginExecutionException: Execution
generate-springmvc-api-docs of goal
com.phoenixnap.oss:springmvc-raml-plugin:0.2.1:generate-springmvc-api-docs
failed: 0

at
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)

at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)

... 20 more

Caused by: java.lang.ArrayIndexOutOfBoundsException: 0

at
com.phoenixnap.oss.ramlapisync.parser.SpringMvcResourceParser.getHttpMethodAndName(SpringMvcResourceParser.java:371)

at
com.phoenixnap.oss.ramlapisync.parser.SpringMvcResourceParser.extractAndAppendResourceInfo(SpringMvcResourceParser.java:430)

at
com.phoenixnap.oss.ramlapisync.parser.ResourceParser.getMethodsFromService(ResourceParser.java:85)

at
com.phoenixnap.oss.ramlapisync.parser.ResourceParser.extractResourceInfo(ResourceParser.java:351)

at
com.phoenixnap.oss.ramlapisync.generation.RamlGenerator.lambda$generateRamlForClasses$0(RamlGenerator.java:240)

at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)

at
com.phoenixnap.oss.ramlapisync.generation.RamlGenerator.generateRamlForClasses(RamlGenerator.java:239)

at
com.phoenixnap.oss.ramlapisync.plugin.SpringMvcRamlApiSyncMojo.generateRaml(SpringMvcRamlApiSyncMojo.java:92)

at
com.phoenixnap.oss.ramlapisync.plugin.SpringMvcRamlApiSyncMojo.execute(SpringMvcRamlApiSyncMojo.java:120)

at
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

... 21 more

**Comment by kurtpa** [comment]
You are using a very old version of the plugin (0.2.1) we have fixed that issue in a subsequent release. Upgrade your version to a more recent release and this should no longer be an issue

**Comment by vishalmahuli** [comment]
Thanks! Will try that, can you please tell me the most recent version?

**Comment by kurtpa** [comment]
Currently 0.7.2 is the latest. You can find the latest releases here: https://github.com/phoenixnap/springmvc-raml-plugin/releases

**Comment by vishalmahuli** [comment]
Help me solve this one please.

Could not save raml - directory enclosing
/Users/vmahuli/cpcontract-api/src/main/resources/public/raml/api.raml does
not exist

java.io.FileNotFoundException:
/Users/vmahuli/cpcontract-api/src/main/resources/public/raml/api.raml (No
such file or directory)

at java.io.FileOutputStream.open0(Native Method)

at java.io.FileOutputStream.open(FileOutputStream.java:270)

at java.io.FileOutputStream.<init>(FileOutputStream.java:213)

at java.io.FileOutputStream.<init>(FileOutputStream.java:162)

at
com.phoenixnap.oss.ramlapisync.generation.RamlGenerator.outputRamlToFile(RamlGenerator.java:219)

at
com.phoenixnap.oss.ramlapisync.plugin.SpringMvcRamlApiSyncMojo.generateRaml(SpringMvcRamlApiSyncMojo.java:118)

at
com.phoenixnap.oss.ramlapisync.plugin.SpringMvcRamlApiSyncMojo.execute(SpringMvcRamlApiSyncMojo.java:143)

at
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)

at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)

at
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)

at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)

at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)

at
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)

at
org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)

at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)

at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)

at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)

at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)

at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)

at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)

at
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)

at
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)

at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by vishalmahuli** [comment]
Thank you, My build is successful. Could you please let me know where to
find the generated raml file?

**Comment by vishalmahuli** [comment]
suppose the relative path where the raml is to be saved is a/b/c/api.raml, Even though the build is successful that api.raml isn't created in the specified path.

**Comment by vishalmahuli** [comment]
Found it! I had to create a file in that location prior to running this tool. Tool was of great help! Thanks!

**Comment by FelixHerz** [comment]
I get the same error with version 0.8.9

```
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-springmvc-endpoints of goal com.phoenixnap.oss:springmvc-raml-plugin:0.7.2:generate-springmvc-en
dpoints failed: -1
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at com.phoenixnap.oss.ramlapisync.naming.NamingHelper.getActionName(NamingHelper.java:381)
        at com.phoenixnap.oss.ramlapisync.data.ApiActionMetadata.getName(ApiActionMetadata.java:193)
        at com.phoenixnap.oss.ramlapisync.data.ApiActionMetadata.parseResponse(ApiActionMetadata.java:177)
        at com.phoenixnap.oss.ramlapisync.data.ApiActionMetadata.<init>(ApiActionMetadata.java:73)
        at com.phoenixnap.oss.ramlapisync.data.ApiResourceMetadata.addApiCall(ApiResourceMetadata.java:60)
        at com.phoenixnap.oss.ramlapisync.generation.RamlParser.checkResource(RamlParser.java:161)
        at com.phoenixnap.oss.ramlapisync.generation.RamlParser.extractControllers(RamlParser.java:101)
        at com.phoenixnap.oss.ramlapisync.plugin.SpringMvcEndpointGeneratorMojo.generateEndpoints(SpringMvcEndpointGeneratorMojo.java:167)
        at com.phoenixnap.oss.ramlapisync.plugin.SpringMvcEndpointGeneratorMojo.execute(SpringMvcEndpointGeneratorMojo.java:332)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
```

**Comment by bendem** [comment]
`com.phoenixnap.oss:springmvc-raml-plugin:0.7.2:generate-springmvc-en`

that's not 0.8.9...
